### ISSUE TITLE
'Dimigo rest API' has 2 hosts

### ISSUE THREAD

**Issue by h4wldev** [jnjcomu/dets-online#1]
In `settings.php` what you wrote, dimigo rest api host is only 'https://api.dimigo.hs.kr'.

But it has 2 hosts **'development(api.dimigo.org)'** or **'production(api.dimigo.hs.kr)'**

and in **DIMIGO REST API ver 1.3** production hosts divided 3.

- http://api.dimigo.hs.kr
- https://api.dimigo.hs.kr
- http://dapi.dimigo.hs.kr

So, I recommend, divide the host with environment.

You can check more info in rest api docs

**Comment by junkijin** [comment]
Thank you. I add your advice in `settings.php` example.
